routes/web.php
<?php

use App\Http\Controllers\ChartController;
use App\Http\Controllers\DefaultPageController;
use App\Http\Controllers\IngredientController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [DefaultPageController::class, 'index'])->name('home.index');

Route::resource('ingredients', IngredientController::class);
Route::resource('purchases', PurchaseController::class);

Route::get('/search', [SearchController::class, 'index'])->name('search.index');
Route::post('/search', [SearchController::class, 'search'])->name('search.search');
Route::get('/search-by-year-and-month', [SearchController::class, 'searchByMonthAndYear'])->name('search.custom');

app/Models/Purchase.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    use HasFactory;

    protected $fillable = [
        'ingredient_id', 'qty', 'price', 'date', 'desc'
    ];

    public function ingredient()
    {
        return $this->belongsTo('App\Models\Ingredient');
    }
}

app/Http/Controllers/PurchaseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ingredient;
use App\Models\Purchase;
use Illuminate\Http\Request;

class PurchaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('purchase.index', [
            'purchases' => Purchase::with('ingredient')->orderBy('date', 'ASC')->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('purchase.create', [
            'purchase' => new Purchase(),
            'ingredients' => Ingredient::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'ingredient_id' => 'required',
            'date' => 'required',
            'qty' => 'required',
            'price' => 'required',
            'desc' => 'string'
        ]);
        Purchase::create($validatedData);
        return redirect()->route('purchases.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function show(Purchase $purchase)
    {
        return view('purchase.show', [
            'purchase' => $purchase
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function edit(Purchase $purchase)
    {
        return view('purchase.edit', [
            'purchase' => $purchase,
            'ingredients' => Ingredient::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Purchase $purchase)
    {
        $validatedData = $request->validate([
            'ingredient_id' => 'required',
            'date' => 'required',
            'qty' => 'required',
            'price' => 'required',
            'desc' => 'string'
        ]);
        $purchase->update($validatedData);
        return redirect()->route('purchases.show', $purchase->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Purchase  $purchase
     * @return \Illuminate\Http\Response
     */
    public function destroy(Purchase $purchase)
    {
        $purchase->delete();
        return redirect()->route('purchases.index');
    }
}

resources/views/purchase/_form.blade.php
<div class="form-group">
    <label>Nama Barang</label>
    <select name="ingredient_id" class="form-control @error('ingredient_id') is-invalid @enderror">
        @foreach ($ingredients as $ingredient)
            <option value="{{ $ingredient->id }}" {{ (old('ingredient_id', $purchase->ingredient_id) == $ingredient->id) ? 'selected' : '' }}>
                {{ $ingredient->name }}
            </option>
        @endforeach
    </select>
    @error('ingredient_id')
        <small class="invalid-feedback" role="alert">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label>QTY</label>
    <input type="number" name="qty" class="form-control @error('qty') is-invalid @enderror" value="{{ old('qty', $purchase->qty) }}">
    @error('qty')
        <small class="invalid-feedback" role="alert">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label>Harga</label>
    <input type="number" name="price" class="form-control @error('price') is-invalid @enderror" value="{{ old('price', $purchase->price) }}">
    @error('price')
        <small class="invalid-feedback" role="alert">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label>Tanggal</label>
    <input type="date" name="date" class="form-control @error('date') is-invalid @enderror" value="{{ old('date', $purchase->date) }}">
    @error('date')
        <small class="invalid-feedback" role="alert">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label>Keterangan</label>
    <textarea name="desc" cols="30" rows="4" class="form-control @error('desc') is-invalid @enderror">{{ old('desc', $purchase->desc) }}</textarea>
    @error('desc')
        <small class="invalid-feedback" role="alert">{{ $message }}</small>
    @enderror
</div>

resources/views/purchase/create.blade.php
@extends('layouts.main')

@section('title', 'Pembelian')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-body">
                    <h3 class="card-title">Tambah Pembelian</h3>
                    <form action="{{ route('purchases.store') }}" method="POST">
                        @csrf
                        @include('purchase._form')
                        <div class="form-group">
                            <button class="btn btn-primary btn-sm" type="submit"><i class="bi bi-check2 mr-2"></i>Simpan</button>
                            <a href="{{ route('ingredients.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left mr-2"></i>Kembali</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/purchase/edit.blade.php
@extends('layouts.main')

@section('title', 'Pembalian')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-body">
                    <h3 class="card-title">Edit Pembelian</h3>
                    <form action="{{ route('purchases.update', $purchase->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        @include('purchase._form')
                        <div class="form-group">
                            <button class="btn btn-primary btn-sm" type="submit"><i class="bi bi-check2 mr-2"></i>Ubah</button>
                            <a href="{{ route('ingredients.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left mr-2"></i>Kembali</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/purchase/index.blade.php
@extends('layouts.main')

@section('title', 'Pembelian')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-header">
                    <h3 class="card-title">Data Pembelian</h3>
                    <small>Semua data pembelian yang tersimpan di sistem</small>
                </div>
                <div class="card-body">
                    <a href="{{ route('purchases.create') }}" class="mb-3 btn btn-sm btn-success mt-3"><i class="bi bi-cart-plus mr-2"></i>Tambah</a>
                    <div class="table-responsive">
                        <table id="purchasesData" class="mt-3 table-sm table table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Nama Barang</th>
                                    <th>QTY</th>
                                    <th>Harga</th>
                                    <th>Tanggal beli</th>
                                    <th>#</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($purchases as $purchase)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $purchase->ingredient->name }}</td>
                                    <td>{{ $purchase->qty }}</td>
                                    <td>Rp. {{ number_format($purchase->price,2,",",".") }}</td>
                                    <td>{{ $purchase->date }}</td>
                                    <td>
                                        <a href="{{ route('purchases.show', $purchase->id) }}"
                                            class="btn btn-sm btn-info"><i class="bi bi-cart-check mr-2"></i>Detail</a>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="6" class="text-center text-muted"><i>Pembelian kosong</i></td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('links')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/datatables.min.css"/>
@endpush
@push('scripts')
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.23/datatables.min.js"></script>
<script>
$(document).ready( function () {
    $('#purchasesData').DataTable();
});
</script>
@endpush

resources/views/purchase/show.blade.php
@extends('layouts.main')

@section('title', 'Pembelian')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-body">
                    <h3 class="card-title">Detail Pembelian</h3>

                    <table class="table table-hover table-bordered mt-3 mb-3">
                        <tr>
                            <th>Nama Barang</th>
                            <td>{{ $purchase->ingredient->name }}</td>
                        </tr>
                        <tr>
                            <th>QTY</th>
                            <td>{{ $purchase->qty }}</td>
                        </tr>
                        <tr>
                            <th>Harga</th>
                            <td>Rp. {{ number_format($purchase->price,2,",",".") }}</td>
                        </tr>
                        <tr>
                            <th>Tanggal</th>
                            <td>{{ $purchase->date }}</td>
                        </tr>
                        <tr>
                            <th>Keterangan</th>
                            <td>{{ $purchase->desc }}</td>
                        </tr>
                    </table>
                    <div class="form-group">
                        <a href="{{ route('purchases.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left mr-2"></i>Kembali</a>
                        <a href="{{ route('purchases.edit', $purchase->id) }}" class="btn btn-sm btn-warning"><i class="bi bi-pencil mr-2"></i>Edit</a>
                        <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteModal">
                            <i class="bi bi-trash mr-2"></i> Hapus
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Hapus barang</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form action="{{ route('purchases.destroy',  $purchase->id) }}" method="POST">
            <div class="modal-body">
                <div class="alert alert-danger">Hapus pembelian ini?</div>
                    @csrf
                    @method('DELETE')
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal"><i class="bi bi-x-circle mr-2"></i>Batal</button>
                <button class="btn btn-sm btn-danger"><i class="bi bi-trash mr-2"></i>Hapus</button>
        </form>
        </div>
    </div>
</div>
@endsection