routes/web.php
<?php

use App\Http\Controllers\ChartController;
use App\Http\Controllers\DefaultPageController;
use App\Http\Controllers\IngredientController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [DefaultPageController::class, 'index'])->name('home.index');

Route::resource('ingredients', IngredientController::class);
Route::resource('purchases', PurchaseController::class);

Route::get('/search', [SearchController::class, 'index'])->name('search.index');
Route::post('/search', [SearchController::class, 'search'])->name('search.search');
Route::get('/search-by-year-and-month', [SearchController::class, 'searchByMonthAndYear'])->name('search.custom');

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ingredient extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'desc'
    ];

    public function purchases()
    {
        return $this->hasMany('App\Models\Purchase');
    }
}

app/Http/Controllers/IngredientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ingredient;
use Illuminate\Http\Request;

class IngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('ingredient.index', [
            'ingredients' => Ingredient::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ingredient.create', [
            'ingredient' => new Ingredient()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'desc' => 'required'
        ]);
        Ingredient::create([
            'name' => $validatedData['name'],
            'desc' => $validatedData['desc']
        ]);
        return redirect()->route('ingredients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function show(Ingredient $ingredient)
    {
        return view('ingredient.show', [
            'ingredient' => $ingredient
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {
        return view('ingredient.edit', [
            'ingredient' => $ingredient
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ingredient $ingredient)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'desc' => 'required'
        ]);
        $ingredient->update([
            'name' => $validatedData['name'],
            'desc' => $validatedData['desc']
        ]);
        return redirect()->route('ingredients.show', $ingredient->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ingredient $ingredient)
    {
        $ingredient->delete();
        return redirect()->route('ingredients.index');
    }
}

resources/views/ingredient/_form.blade.php
<div class="form-group">
    <label>Nama Barang</label>
    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" autofocus autocomplete="off" value="{{ old('name', $ingredient->name) }}">
    @error('name')
        <small class="invalid-feedback" role="alert">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label>Keterangan</label>
    <textarea name="desc" cols="30" rows="4" class="form-control @error('desc') is-invalid @enderror">{{ old('desc', $ingredient->desc) }}</textarea>
    @error('desc')
        <small class="invalid-feedback" role="alert">{{ $message }}</small>
    @enderror
</div>

resources/views/ingredient/create.blade.php
@extends('layouts.main')

@section('title', 'Bahan - Bahan')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-body">
                    <h3 class="card-title">Tambah Barang</h3>
                    <form action="{{ route('ingredients.store') }}" method="POST">
                        @csrf
                        @include('ingredient._form')
                        <div class="form-group">
                            <button class="btn btn-primary btn-sm" type="submit"><i class="bi bi-check2 mr-2"></i>Simpan</button>
                            <a href="{{ route('ingredients.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left mr-2"></i>Kembali</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ingredient/edit.blade.php
@extends('layouts.main')

@section('title', 'Bahan - Bahan')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-body">
                    <h3 class="card-title">Edit Barang</h3>
                    <form action="{{ route('ingredients.update', $ingredient->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        @include('ingredient._form')
                        <div class="form-group">
                            <button class="btn btn-primary btn-sm" type="submit"><i class="bi bi-check2 mr-2"></i>Ubah</button>
                            <a href="{{ route('ingredients.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left mr-2"></i>Kembali</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ingredient/index.blade.php
@extends('layouts.main')

@section('title', 'Bahan - Bahan')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-header">
                    <h3 class="card-title">Data Barang</h3>
                    <small>Semua data barang yang tersimpan di sistem</small>
                </div>
                <div class="card-body">
                    <a href="{{ route('ingredients.create') }}" class="btn btn-sm btn-success mt-3"><i class="bi bi-bag-plus mr-2"></i>Tambah</a>
                    <table class="mt-3 table-sm table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Barang</th>
                                <th>Keterangan</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($ingredients as $ingredient)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $ingredient->name }}</td>
                                <td>{{ $ingredient->desc }}</td>
                                <td>
                                    <a href="{{ route('ingredients.show', $ingredient->id) }}"
                                        class="btn btn-info btn-sm"><i class="bi bi-bag-check mr-2"></i>Detail</a>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="4" class="text-center text-muted"><i>Barang kosong</i></td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ingredient/show.blade.php
@extends('layouts.main')

@section('title', 'Bahan - Bahan')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-body">
                    <h3 class="card-title">Detail Barang</h3>

                    <table class="table table-hover table-bordered mt-3 mb-3">
                        <tr>
                            <th>Nama Barang</th>
                            <td>{{ $ingredient->name }}</td>
                        </tr>
                        <tr>
                            <th>Keterangan</th>
                            <td>{{ $ingredient->desc }}</td>
                        </tr>
                    </table>
                    <div class="form-group">
                        <a href="{{ route('ingredients.index') }}" class="btn btn-sm btn-secondary"><i class="bi bi-arrow-left mr-2"></i>Kembali</a>
                        <a href="{{ route('ingredients.edit', $ingredient->id) }}" class="btn btn-sm btn-warning"><i class="bi bi-pencil mr-2"></i>Edit</a>
                        <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteModal">
                            <i class="bi bi-trash mr-2"></i>Hapus
                        </button>
                    </div>

                    <h3 class="card-title mt-3">Riwayat Pembelian</h3>
                    <table class="table table-sm table-bordered table-hover mt-2 mb-3">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Tanggal Pembelian</th>
                                <th>QTY</th>
                                <th>Harga</th>
                                <th>Keterangan</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($ingredient->purchases as $purchase)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $purchase->date }}</td>
                                    <td>{{ $purchase->qty }}</td>
                                    <td>Rp. {{ number_format($purchase->price,2,",",".") }}</td>
                                    <td>{{ $purchase->desc }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="text-center text-muted"><i>Tidak ada Pembelian atas barang ini</i></td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Hapus barang</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form action="{{ route('ingredients.destroy',  $ingredient->id) }}" method="POST">
            <div class="modal-body">
                <div class="alert alert-danger">Hapus barang ini?</div>
                    @csrf
                    @method('DELETE')
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal"><i class="bi bi-x-circle mr-2"></i>Batal</button>
                <button class="btn btn-danger btn-sm"><i class="bi bi-trash mr-2"></i>Hapus</button>
        </form>
        </div>
    </div>
</div>
@endsection